@startuml
class InterestedIn {
    + SportId : int <<get>> <<set>>
    + UserId : string <<get>> <<set>> = "0"
    + Skill : int <<get>> <<set>> = 5
}
InterestedIn o-> "Sport" Sport
InterestedIn o-> "UserInterested" ApplicationUser
@enduml
